project:
  type: website
  output-dir: docs

website:
  title: "About"
  sidebar:
    style: "floating"
    logo: profile.jpeg
    contents:
      - index.qmd
      - section: "Work Samples"
        contents:
          - sql_demo.qmd
          - bring_current.qmd
          - prophet_model.qmd

format: 
  html: 
    css: styles.css