project:
  type: website
  output-dir: docs

website:
  title: "Guy McAtee"
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - section: "Data Work"
        contents:
          - bring_current.qmd

format: 
  html: 
    css: styles.css