project:
  type: website
  output-dir: docs

website:
  title: "About"
  sidebar:
    style: "floating"
    search: true
    logo: profile.jpeg
    contents:
      - index.qmd
      - section: "Data Work"
        contents:
          - bring_current.qmd

format: 
  html: 
    css: styles.css