---
title: "Guy McAtee"
format:
  html:
    page-layout: full
downloads: [resume_pdf]
---
gmact16@gmail.com <br>
Pleasant Grove, UT

Code for this website: <https://github.com/gmcatee/portfolio/tree/main>

::: columns
::: {.column width="45%"}
## Skills

<div class="skills_list">
-   GitHub actions & GitLab pipelines for CI/CD

-   AWS & DynamoDB

-   SQL (Snowflake, MySQL, Posgres, Presto)

-   Datawarehouse management using dbt Core and Python

-   A/B testing, forecasting, stats

-   Build interactive Dashboards

    -   Tableau, RShiny, Graveler, BS4, ZenDash

-   Data storytelling and clear communication
</div>

::: {.download_btn}
```{css}
#| echo: false

.btn-default,
.btn-default:hover,
.btn-default:active {
  font-size: 20px;
  color: black;
  background-color: transparent;
  border-color: transparent;
}

.btn-default:hover {
  color: grey;
  transition: 0.2s;
}
```

```{r, echo=FALSE}
library(downloadthis)
download_link(
  link = "https://github.com/gmcatee/portfolio/blob/main/GuyMcAtee_Resume.pdf",
  button_label = "Download Resumé",
  button_type = "default",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```
:::

:::

::: {.column width="5%"}
<!-- empty for space -->
:::

::: {.column width="50%"}
## Recent Work

### Analytics Engineer, Sunbound

-   One-man team for end to end analytics

-   Managing a Kimball Method based dbt Core project orchestrated w/ GitLab CI/CD pipelines

-   Managing Snowflake and the growing demand for Claude (LLM) interactions with data

-   Building visualizations in Tableau for stakeholders throughout the business

### Senior Business Intelligence Engineer, Limble CMMS

-   Building data solutions for Finance (GTM framework, Revenue Cohort Analysis etc.)

-   Manage various data models in Snowflake via DBT

-   Troubleshoot Five Tran data connections using custom API connectors

### Business Intelligence Engineer, Snap! Finance

-   Data migration of a Loan Management System

-   Manage R Shiny dashboards hosted on the company's Posit Connect server

-   Clean and prepare data from various sources (AWS S3, Presto/Postgres databases)

-   Automate reports (Anomaly detection, daily scripts, PowerPoints)

-   Communicate portfolio health to managers and C-Suite

## Education

### Utah Valley University

-   BS Information Systems, Business Intelligence 2016-2020
:::
:::
